### ISSUE TITLE
S3 Access Denied Error

### ISSUE THREAD

**Issue by wessankey** [awslabs/real-time-analytics-spark-streaming#2]
Stack creation is failing when attempting to retrieve the VPC template defined in the `VPCStackQ` resource. It's retrieving the template from the URL below, but the object at that location doesn't have public read access.

https://s3.amazonaws.com/quickstart-reference/aws/vpc/latest/templates/aws-vpc.template

**Comment by pbrose** [comment]
I am facing the same issue - is there any solution?

**Comment by pbrose** [comment]
It looks like the location of the quick-start VPC template changed in S3. I could successfully run the template by changing the location to https://aws-quickstart.s3.amazonaws.com/quickstart-aws-vpc/templates/aws-vpc.template and created a PR at https://github.com/awslabs/real-time-analytics-spark-streaming/pull/3

**Comment by aijunpeng** [comment]
We have added your request to our solution backlog items and it will be fixed in future
solution releases. We thank you for your contribution.

**Comment by aassadza** [comment]
This is addressed with version v1.1.0.
